### ISSUE TITLE
Pin.exe can't make memdump

### ISSUE THREAD

**Issue by smlijun** [sslab-gatech/winnie#16]
I'm trying to use harnessgen. But if I use pin.exe with "all" opiton it can't make memdump even if Administrator permission. Do you know the general reason for this problem?

**Comment by gonbbb** [comment]
@Jinmo 
I'm struggling with this too. Did you run the script below? 

```
# Trace API calls
pin.exe -t source/tools/Tracer/Release/Tracer.dll ^
  -logdir "cor1_1" -trace_mode "all" ^
  -only_to_target "test.exe" -only_to_lib "test.dll" ^
  -- test.exe input1

# Run harness synthesizer on single trace which starts from START_FUNCTION(...)
python3 synthesizer.py harness -t cor1_1/drltrace.PID.log -d cor1_1/memdump -s START_FUNCTION
```

https://github.com/sslab-gatech/winnie/tree/master/harnessgen#one-trace

**Comment by stong** [comment]
I'm really sorry I can't help with these lately. I see these in my inbox and I feel guilty. But I just don't have time to maintain the project T_T ;-; Please forgive me

**Comment by Jinmo** [comment]
I've got DM from the original reporter in January and investigated the specific issue.. It was because of multiple DLLs with the same name but different paths loaded into the same process.

## The root cause

The memory dump is generated for each detected function calls; in trace_mode == 'all', it traces these kind of calls:

- calls from target (`-only_to_target`) to module (`-only_to_lib`)
- calls from module to target as well (when `-print_callback=1`, default: `0`)

Once any call with pointer arguments is detected, the memory dump should contain some information. So empty memdump file would mean that there are no calls detected between them.

## Solution

One common issue was that because `only_to_lib` and `only_to_target` is matched like `strstr(loaded_library_name, "user_argument")`, it should be an accurate absolute path, or just the filename part. To examine this, try checking the existence of `LIBRARY MODULE START ADDR:` and `TARGET MODULE START ADDR:` string in the drltrace log file. If there isn't, it means that the tracer couldn't find the matching library/target.

In that case, try using the exact library/executable name shown in the log file, or just a unique part of the filename e.g. `test.exe` instead of `C:\Users\...\test.exe`.

p.s. I'm also a little bit busy nowadays so didn't have time to investigate the reported issues. Sorry :(

**Comment by gonbbb** [comment]
Thank you. I'll try a little harder.

**Comment by stong** [comment]
Closed due to inactivity
