### ISSUE TITLE
Why is the calling convention either stdcall or cdecl in harnessgen?

### ISSUE THREAD

**Issue by gonbbb** [sslab-gatech/winnie#18]
When call the `serialize` method, each function decided on `stdcall` or `cdecl` as the calling convention.
I think there are `fastcall` other than `stdcall` and `cdecel`, for example, but what is the intention?

https://github.com/sslab-gatech/winnie/blob/b046bcee1befb8f5b173ef38dbd0cac351f89ed9/harnessgen/util/ida_func_type.py#L20

Thanks

**Comment by Jinmo** [comment]
You're right. In fact, that code is written because we didn't see any `__fastcall`s in our experiments.
(For x64, since cdecl behaves the same as fastcall, we just used cdecl)
Since the value is forwarded directly into the generated harnesses, I think just returning `__fastcall` on `CM_CC_FASTCALL` might be enough to fix the issue.

https://github.com/sslab-gatech/winnie/blob/7ed8209491b334614f887f7d55f7ea41f875d8c2/harnessgen/common.py#L789

**Comment by gonbbb** [comment]
Thank you for reply.

If there is no need to choose between `fastcall` and `cdecl`, 
I think it would be better to just return the calling convention, like ` 'cc': return fi.cc`
