### ISSUE TITLE
How to debug winnie?

### ISSUE THREAD

**Issue by dms1lva** [sslab-gatech/winnie#42]
I am trying to figure out why my target program crashes when running with winnie. I would like to debug winnie using visual studio but it fails to inject the forkserver dll when doing so. I set afl-fuzz as the startup project.

Not sure if related but FindModule in process.c does not seem to receive a valid process handle.
```c	
BOOL ok = GetProcessImageFileNameA(hProcess, processName, 256);
fprintf(stderr, "%s", processName);
```

I added this piece of code in FindModule and it works fine when running afl-fuzz, but not under a debugger.

Any advice on how to debug winnie?
Or on how to debug a target process that crashes only under winnie?

**Comment by stong** [comment]
You should avoid using VS debugger. I recommend x64dbg.

> GetProcessImageFileNameA

I'm not sure why this function would fail under debugger. I suspect it could be due to something done by Visual Studio debugger.

>  Or on how to debug a target process that crashes only under winnie?

The best advice I can give in general is to refer to [these steps in the README](https://github.com/sslab-gatech/winnie#troubleshooting). It's hard to say exactly what is wrong without more information on the specific target application.

**Comment by stong** [comment]
Closed due to inactivity.
